#ifndef MSG_STRUCT_H
#define MSG_STRUCT_H
#define NICK_LEN 128
#define INFOS_LEN 128
#define CHAN_LEN 128
#define FILENAME_LEN 128

enum msg_type {
	UNKNOWN_COMMAND, 
	NICKNAME_NEW,
	NICKNAME_SUCCESS,
	NICKNAME_ERROR,
	NICKNAME_LIST,
	NICKNAME_INFOS,
	NICKNAME_INFOS_ERROR,
	WHOAMI,
	ECHO_SEND,
	UNICAST_SEND,
	UNICAST_SUCCESS,
	UNICAST_ERROR, 
	BROADCAST_SEND,
	BROADCAST_SUCCESS,
	BROADCAST_ERROR,
	MULTICAST_CREATE,
	MULTICAST_CREATE_SUCCESS,
	MULTICAST_CREATE_ERROR,
	MULTICAST_LIST,
	MULTICAST_JOIN,
	MULTICAST_JOIN_SUCCESS,
	MULTICAST_JOIN_ERROR,
	MULTICAST_SEND,
	MULTICAST_SEND_SUCCESS,
	MULTICAST_SEND_ERROR,
	MULTICAST_QUIT,
	MULTICAST_QUIT_SUCCESS,
	MULTICAST_QUIT_ERROR,
	FILE_REQUEST,
	FILE_ACCEPT,
	FILE_REJECT,
	FILE_SEND,
	FILE_ACK,
	FILE_EXISTENCE_ERROR,
	RECEIVER_EXISTENCE_ERROR,
	TRY_AGAIN_Y_N,
	QUIT_REQUEST,
	SERVER_QUIT
};

struct message {
	int pld_len;
	char nick_sender[NICK_LEN];
	enum msg_type type;
	char infos[INFOS_LEN];
};

static char* msg_type_str[] = {
	"UNKNOWN_COMMAND",
	"NICKNAME_NEW",
	"NICKNAME_SUCCESS",
	"NICKNAME_ERROR",
	"NICKNAME_LIST",
	"NICKNAME_INFOS",
	"NICKNAME_INFOS_ERROR",
	"WHOAMI",
	"ECHO_SEND",
	"UNICAST_SEND", 
	"UNICAST_SUCCESS",
	"UNICAST_ERROR",
	"BROADCAST_SEND",
	"BROADCAST_SUCCESS",
	"BROADCAST_ERROR",
	"MULTICAST_CREATE",
	"MULTICAST_CREATE_SUCCESS",
	"MULTICAST_CREATE_ERROR",
	"MULTICAST_LIST",
	"MULTICAST_JOIN",
	"MULTICAST_JOIN_SUCCESS",
	"MULTICAST_JOIN_NOTIF",
	"MULTICAST_SEND",
	"MULTICAST_SEND_SUCCESS",
	"MULTICAST_SEND_ERROR",
	"MULTICAST_QUIT",
	"MULTICAST_QUIT_SUCCESS",
	"MULTICAST_QUIT_ERROR",
	"FILE_REQUEST",
	"FILE_ACCEPT",
	"FILE_REJECT",
	"FILE_SEND",
	"FILE_ACK",
	"FILE_EXISTENCE_ERROR",
	"RECEIVER_EXISTENCE_ERROR",
	"TRY_AGAIN_Y_N",
	"QUIT_REQUEST",
	"SERVER_QUIT"
};

#endif


